apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster-primary
spec:
  type: LoadBalancer
  ports:
    - port: 3307
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
    v1alpha1.mysql.oracle.com/role: primary