apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tomcat-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /app
        backend:
          serviceName: app-tomcat-service
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-tomcat-service
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: app-tomcat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tomcat-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-tomcat
  template:
    metadata:
      labels:
        app: app-tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:9.0.29-jdk11-openjdk
        ports:
        - containerPort: 8080
