apiVersion: v1
kind: Service
metadata:
  name: app-pim-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    app: app-pim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pim-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-pim
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-pim
    spec:
      containers:
      - name: pim
        image: alexandersarson/pim:273
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 400m
            memory: 450Mi
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: app-pim-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-pim-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
     name: cpu
     target:
       type: Utilization
       averageUtilization: 80